spring:
  # database
  # --- rds postgresql db --- #
  datasource:
    url: jdbc:postgresql://database-pionada-ai-poc-13.cuerrc1vwpjd.ap-northeast-2.rds.amazonaws.com:5023/vs_dp_data_service
    username: pionada_ai_poc
    password: pocAiPionada1#
    hikari:
      maximum-pool-size: 4

  # --- local H2 db --- #
#      url: jdbc:h2:tcp://localhost/~/visang-dataportal #4?
##    url: jdbc:h2:file:C:\Users\user
#    #url: jdbc:h2:file:C:/visang/test
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis: # type을 쉽게 쓰기 위해서 dto 패키지를 type-aliaes에 설정
  mapper-locations: /mappers/**/*.xml
  type-aliases-package: visang.dataplatform.dataportal.model
  config-location: classpath:mybatis/mybatis-config.xml


springfox:
  documentation:
    swagger-ui:
      base-url: /api

logging:
  config:
    classpath: logback-spring.xml